// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kclbdxvoownosavvwaap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjbGJkeHZvb3dub3NhdnZ3YWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTI0NDYsImV4cCI6MjA3MzI2ODQ0Nn0.NVIfcfNdN1TJ4sHn90yJWSZwpt3lkdbxqkLD6Zar5sQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});